# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule RasaApi.Model.ActionRequest do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :name,
    :policy,
    :confidence
  ]

  @type t :: %__MODULE__{
    name: String.t,
    policy: String.t | nil,
    confidence: float() | nil
  }
end

defimpl Poison.Decoder, for: RasaApi.Model.ActionRequest do
  def decode(value, _options) do
    value
  end
end

