# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule RasaApi.Model.BotMessage do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :recipient_id,
    :text,
    :image,
    :buttons,
    :attachement
  ]

  @type t :: %__MODULE__{
    recipient_id: String.t | nil,
    text: String.t | nil,
    image: String.t | nil,
    buttons: [BotMessageButtons] | nil,
    attachement: [BotMessageAttachement] | nil
  }
end

defimpl Poison.Decoder, for: RasaApi.Model.BotMessage do
  import RasaApi.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:buttons, :list, RasaApi.Model.BotMessageButtons, options)
    |> deserialize(:attachement, :list, RasaApi.Model.BotMessageAttachement, options)
  end
end

