# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule RasaApi.Model.Domain do
  @moduledoc """
  The bot&#39;s domain.
  """
  alias RasaApi.Model.DomainConfig
  alias RasaApi.Model.SlotDescription
  alias RasaApi.Model.TemplateDescription

  @derive [Poison.Encoder]
  defstruct [
    :config,
    :intents,
    :entities,
    :slots,
    :responses,
    :actions
  ]

  @type t :: %__MODULE__{
    config: DomainConfig | nil,
    intents: [Map] | nil,
    entities: [String.t] | nil,
    slots: %{optional(String.t) => SlotDescription} | nil,
    responses: %{optional(String.t) => TemplateDescription} | nil,
    actions: [String.t] | nil
  }
end

defimpl Poison.Decoder, for: RasaApi.Model.Domain do
  import RasaApi.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:config, :struct, RasaApi.Model.DomainConfig, options)
    |> deserialize(:slots, :map, RasaApi.Model.SlotDescription, options)
    |> deserialize(:responses, :map, RasaApi.Model.TemplateDescription, options)
  end
end

