# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule RasaApi.Model.InlineResponse200 do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :version,
    :minimum_compatible_version
  ]

  @type t :: %__MODULE__{
    version: String.t | nil,
    minimum_compatible_version: String.t | nil
  }
end

defimpl Poison.Decoder, for: RasaApi.Model.InlineResponse200 do
  def decode(value, _options) do
    value
  end
end

