# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule RasaApi.Model.InlineResponse2002 do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :tracker,
    :messages
  ]

  @type t :: %__MODULE__{
    tracker: Tracker | nil,
    messages: [BotMessage] | nil
  }
end

defimpl Poison.Decoder, for: RasaApi.Model.InlineResponse2002 do
  import RasaApi.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:tracker, :struct, RasaApi.Model.Tracker, options)
    |> deserialize(:messages, :list, RasaApi.Model.BotMessage, options)
  end
end

