# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule RasaApi.Model.InlineResponse2001 do
  @moduledoc """
  
  """
  alias RasaApi.Model.Map

  @derive [Poison.Encoder]
  defstruct [
    :fingerprint,
    :model_file,
    :num_active_training_jobs
  ]

  @type t :: %__MODULE__{
    fingerprint: Map | nil,
    model_file: String.t | nil,
    num_active_training_jobs: integer() | nil
  }
end

defimpl Poison.Decoder, for: RasaApi.Model.InlineResponse2001 do
  import RasaApi.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:fingerprint, :struct, RasaApi.Model.Map, options)
  end
end

