# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule RasaApi.Model.Message do
  @moduledoc """
  
  """
  alias RasaApi.Model.ParseResult

  @derive [Poison.Encoder]
  defstruct [
    :text,
    :sender,
    :parse_data
  ]

  @type t :: %__MODULE__{
    text: String.t,
    sender: String.t,
    parse_data: ParseResult | nil
  }
end

defimpl Poison.Decoder, for: RasaApi.Model.Message do
  import RasaApi.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:parse_data, :struct, RasaApi.Model.ParseResult, options)
  end
end

