# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule RasaApi.Model.TrainingRequest do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :domain,
    :config,
    :nlu,
    :stories,
    :force,
    :save_to_default_model_directory
  ]

  @type t :: %__MODULE__{
    domain: String.t | nil,
    config: String.t,
    nlu: String.t | nil,
    stories: String.t | nil,
    force: boolean() | nil,
    save_to_default_model_directory: boolean() | nil
  }
end

defimpl Poison.Decoder, for: RasaApi.Model.TrainingRequest do
  def decode(value, _options) do
    value
  end
end

