# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule RasaApi.Api.Domain do
  @moduledoc """
  API calls for all endpoints tagged `Domain`.
  """

  alias RasaApi.Connection
  import RasaApi.RequestBuilder


  @doc """
  Retrieve the loaded domain
  Returns the domain specification the currently loaded model is using.

  ## Parameters

  - connection (RasaApi.Connection): Connection to server
  - opts (KeywordList): [optional] Optional parameters
  ## Returns

  {:ok, %RasaApi.Model.Domain{}} on success
  {:error, info} on failure
  """
  @spec get_domain(Tesla.Env.client, keyword()) :: {:ok, RasaApi.Model.Domain.t} | {:error, Tesla.Env.t}
  def get_domain(connection, _opts \\ []) do
    %{}
    |> method(:get)
    |> url("/domain")
    |> Enum.into([])
    |> (&Connection.request(connection, &1)).()
    |> evaluate_response([
      { 200, %RasaApi.Model.Domain{}},
      { 401, %RasaApi.Model.Error{}},
      { 403, %RasaApi.Model.Error{}},
      { 406, %RasaApi.Model.Error{}},
      { 500, %RasaApi.Model.Error{}}
    ])
  end
end
